// Store Action Types
export const ACTION_TYPE = 'ACTION_TYPE';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_JWT_DATA = 'SET_JWT_DATA';

export const SET_SHOW_LOADER = "SET_SHOW_LOADER";
export const SET_OPEN_ALERT_DIALOG = "SET_OPEN_ALERT_DIALOG";

export const SET_ENGAGEMENTS = 'SET_ENGAGEMENTS';
export const E_S_SET_GOALS = 'E_S_SET_GOALS';
export const E_S_SET_TARGET_AUDIENCE = 'E_S_SET_TARGET_AUDIENCE';
export const E_S_DEFINE_JOURNEY = 'E_S_DEFINE_JOURNEY';
export const E_S_SET_JOURNEY_BOX = 'E_S_SET_JOURNEY_BOX';
export const E_S_SET_REWARDS_AND_BUDGET = "E_S_SET_REWARDS_AND_BUDGET";
// Application URL's 
export const ACTION_TYPE_URL = '';

export const ES_SET_JOURNEY_DETAILS = 'ES_SET_JOURNEY_DETAILS';
export const ES_SET_ALL_JOURNEYS_DATA = 'ES_SET_ALL_JOURNEYS_DATA';
export const ES_SET_ALL_JOURNEYS_TASKS = 'ES_SET_ALL_JOURNEYS_TASKS';

export const GET_USERS = "GET_USERS";
export const GET_ROLES = "GET_ROLES";

export const SET_ROLES_WITH_PERMISSION_COUNT = "SET_ROLES_WITH_PERMISSION_COUNT";
export const SET_PERMISSIONS = "SET_PERMISSIONS";

export const SET_SUMMARY_TOTALS = "SET_SUMMARY_TOTALS";
